-- Copyright (C) 2026 Bernard BERTRAND
--
-- This file is part of TUT_EGSE_EP.
--
-- This software is governed by the CeCILL license under French law
-- and abiding by the rules of distribution of free software.
-- You can use, modify and/or redistribute the software under the terms
-- of the CeCILL license as circulated by CEA, CNRS and Inria at:
-- http://www.cecill.info
--
-- See LICENSE.txt for the full license text.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity Rx_re_ads7049_clk2x is
    port(
        -- global
        clk        : in  std_logic;
        rst        : in  std_logic;

        -- adc ADS7049
        o_sck      : out std_logic;
        o_cs_n     : out std_logic;
        i_sdi      : in  std_logic;

        -- sortie adc driver
        o_data_rx  : out std_logic_vector(11 downto 0);
        o_ready_rx : out std_logic
    );
end entity Rx_re_ads7049_clk2x;

architecture RTL of Rx_re_ads7049_clk2x is

    type state_type is (start_frame, first_sck_rise, skip_zero_bits, read_data, acquisition);
    signal state : state_type;

    signal sck_reg      : std_logic;
    signal cs_n_reg     : std_logic;
    signal zero_count   : unsigned(1 downto 0);
    signal bit_count    : unsigned(3 downto 0);
    signal acq_count    : unsigned(3 downto 0);
    signal data_rx_int  : std_logic_vector(11 downto 0);

begin

    ------------------------------------------------------------
    -- ADS7049 serial frame.
    -- All logic is synchronous on rising_edge(clk).
    -- o_sck is generated by a register, so SCLK = clk / 2.
    -- i_sdi is sampled while o_sck is low, one clk cycle after
    -- the previous falling edge of o_sck.
    ------------------------------------------------------------
    process(clk) is
    begin
        if rising_edge(clk) then
            if rst = '1' then
                state       <= start_frame;
                sck_reg     <= '0';
                cs_n_reg    <= '1';
                zero_count  <= (others => '0');
                bit_count   <= (others => '0');
                acq_count   <= (others => '0');
                data_rx_int <= (others => '0');
                o_data_rx   <= (others => '0');
                o_ready_rx  <= '0';
            else
                o_ready_rx <= '0';

                case state is

                    when start_frame =>
                        cs_n_reg    <= '0';
                        sck_reg     <= '0';
                        zero_count  <= (others => '0');
                        bit_count   <= (others => '0');
                        acq_count   <= (others => '0');
                        data_rx_int <= (others => '0');
                        state       <= first_sck_rise;

                    when first_sck_rise =>
                        sck_reg <= '1';
                        state   <= skip_zero_bits;

                    when skip_zero_bits =>
                        if sck_reg = '1' then
                            sck_reg <= '0';
                        else
                            if zero_count = 1 then
                                zero_count <= (others => '0');
                                sck_reg    <= '1';
                                state      <= read_data;
                            else
                                zero_count <= zero_count + 1;
                                sck_reg    <= '1';
                            end if;
                        end if;

                    when read_data =>
                        if sck_reg = '1' then
                            sck_reg <= '0';
                        else
                            data_rx_int <= data_rx_int(10 downto 0) & i_sdi;

                            if bit_count = 11 then
                                sck_reg    <= '0';
                                cs_n_reg   <= '1';
                                bit_count  <= (others => '0');
                                acq_count  <= (others => '0');
                                o_data_rx  <= data_rx_int(10 downto 0) & i_sdi;
                                o_ready_rx <= '1';
                                state      <= acquisition;
                            else
                                bit_count <= bit_count + 1;
                                sck_reg   <= '1';
                            end if;
                        end if;

                    when acquisition =>
                        sck_reg   <= '0';
                        cs_n_reg  <= '1';
                        acq_count <= acq_count + 1;

                        if acq_count = 3 then
                            acq_count <= (others => '0');
                            state     <= start_frame;
                        end if;

                end case;
            end if;
        end if;
    end process;

    o_sck  <= sck_reg;
    o_cs_n <= cs_n_reg;

end architecture RTL;
